server:
  port: 80
  
  
 
feign: 
  hystrix: 
    enabled: true
 

eureka: 
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud1-consumer-fegin80 # 这个是服务信息
    prefer-ip-address: true # 表示当鼠标悬浮在服务信息上时，会显示ip、端口号等
    
spring:
  application:
    name: microservicecloud1-consumer-fegin  # 这个是服务名称
    
    
info:
  app.name: microservicecloud1-consumer-fegin
  company.name: www.jrj.com.cn
  build.artifactId: microservicecloud1-consumer-dept-fegin
  build.version: 0.0.1-SNAPSHOT
      
      