server:
  port: 3344
  
spring:
  application:
    name: microservicecloud1-config #服务名称
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zhangyuxiangwang/microservicecloud1-config.git #ssh