server:
  port: 9001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.jrj.springcloud.bean            # 所有bean别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       #mapper所对应的位置
  
spring:
  application:
    name: microservicecloud1-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test                   # 数据库名称
    dbcp2:
      initial-size: 5                                       # 初始化连接数
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka: 
  client: #吧服务注册到eureka上面
    service-url:
      #单机 defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
     # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud1-dept9001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip
    
info:
  app.name: jrj-microservicecloud
  company.name: www.jrj.com.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$